export const NOTE_PUBLISH_SNIPPET_MAX_LENGTH = 280
export const NOTE_ATTACHMENT_MAX_COUNT = 6
export const NOTE_ATTACHMENT_MAX_NAME_LENGTH = 120
export const NOTE_ATTACHMENT_MAX_URI_LENGTH = 2_000_000
