import type { HTMLAttributes } from 'react'

type IconName =
  | 'search'
  | 'journal'
  | 'history'
  | 'settings'
  | 'close'
  | 'storefront'
  | 'voice'
  | 'rooms'
  | 'users'
  | 'edit'
  | 'mic'
  | 'panel'
  | 'chat'
  | 'notes'
  | 'play'
  | 'pause'
  | 'stop'
  | 'timer'
  | 'hourglass'
  | 'rocket_launch'
  | 'moon'
  | 'sun'
  | 'signal'
  | 'logout'
  | 'arrow_back'
  | 'north'
  | 'south'
  | 'send'
  | 'menu_book'
  | 'chevron_left'
  | 'chevron_right'
  | 'keyboard_double_arrow_left'
  | 'keyboard_double_arrow_right'
  | 'book_2'
  | 'status'
  | 'mic_off'
  | 'effects'
  | 'overrides'
  | 'party'
  | 'inventory'
  | 'restart_alt'
  | 'money_bag'
  | 'currency_exchange'
  | 'receipt_long'
  | 'swap_horiz'
  | 'move_item'
  | 'add'
  | 'add_box'
  | 'add_circle'
  | 'add_photo_alternate'
  | 'arrow_drop_down'
  | 'article'
  | 'attach_file'
  | 'auto_awesome'
  | 'block'
  | 'campaign'
  | 'casino'
  | 'celebration'
  | 'check'
  | 'content_copy'
  | 'delete'
  | 'delete_forever'
  | 'diamond'
  | 'event'
  | 'exit_to_app'
  | 'file_download'
  | 'forest'
  | 'format_list_bulleted'
  | 'format_list_numbered'
  | 'format_quote'
  | 'group'
  | 'group_add'
  | 'group_work'
  | 'groups'
  | 'image'
  | 'inventory_2'
  | 'lock'
  | 'map'
  | 'mystery'
  | 'note_add'
  | 'open_in_new'
  | 'person'
  | 'person_add'
  | 'person_check'
  | 'pets'
  | 'publish'
  | 'record_voice_over'
  | 'refresh'
  | 'schedule'
  | 'sell'
  | 'speed'
  | 'subdirectory_arrow_left'
  | 'subdirectory_arrow_right'
  | 'summarize'
  | 'theaters'
  | 'timeline'
  | 'tune'
  | 'undo'
  | 'upload_file'
  | 'visibility'
  | 'visibility_off'
  | 'warning'

interface IconProps extends HTMLAttributes<HTMLSpanElement> {
  name: IconName
}

const MATERIAL_SYMBOLS: Record<IconName, string> = {
  search: 'search',
  journal: 'menu_book',
  history: 'history',
  settings: 'settings',
  close: 'close',
  voice: 'graphic_eq',
  rooms: 'view_list',
  users: 'group',
  edit: 'edit',
  mic: 'mic',
  panel: 'dashboard',
  chat: 'chat',
  notes: 'notes',
  play: 'play_arrow',
  pause: 'pause',
  stop: 'stop',
  timer: 'timer',
  hourglass: 'hourglass_top',
  rocket_launch: 'rocket_launch',
  moon: 'dark_mode',
  sun: 'light_mode',
  signal: 'signal_cellular_alt',
  logout: 'logout',
  arrow_back: 'arrow_back',
  north: 'north',
  south: 'south',
  send: 'send',
  menu_book: 'menu_book',
  chevron_left: 'chevron_left',
  chevron_right: 'chevron_right',
  keyboard_double_arrow_left: 'keyboard_double_arrow_left',
  keyboard_double_arrow_right: 'keyboard_double_arrow_right',
  book_2: 'book_2',
  status: 'circle',
  mic_off: 'mic_off',
  effects: 'tune',
  overrides: 'supervisor_account',
  party: 'groups',
  inventory: 'inventory_2',
  restart_alt: 'restart_alt',
  money_bag: 'money_bag',
  currency_exchange: 'currency_exchange',
  receipt_long: 'receipt_long',
  swap_horiz: 'swap_horiz',
  storefront: 'storefront',
  move_item: 'move_item',
  add: 'add',
  add_box: 'add_box',
  add_circle: 'add_circle',
  add_photo_alternate: 'add_photo_alternate',
  arrow_drop_down: 'arrow_drop_down',
  article: 'article',
  attach_file: 'attach_file',
  auto_awesome: 'auto_awesome',
  block: 'block',
  campaign: 'campaign',
  casino: 'casino',
  celebration: 'celebration',
  check: 'check',
  content_copy: 'content_copy',
  delete: 'delete',
  delete_forever: 'delete_forever',
  diamond: 'diamond',
  event: 'event',
  exit_to_app: 'exit_to_app',
  file_download: 'file_download',
  forest: 'forest',
  format_list_bulleted: 'format_list_bulleted',
  format_list_numbered: 'format_list_numbered',
  format_quote: 'format_quote',
  group: 'group',
  group_add: 'group_add',
  group_work: 'group_work',
  groups: 'groups',
  image: 'image',
  inventory_2: 'inventory_2',
  lock: 'lock',
  map: 'map',
  mystery: 'mystery',
  note_add: 'note_add',
  open_in_new: 'open_in_new',
  person: 'person',
  person_add: 'person_add',
  person_check: 'person_check',
  pets: 'pets',
  publish: 'publish',
  record_voice_over: 'record_voice_over',
  refresh: 'refresh',
  schedule: 'schedule',
  sell: 'sell',
  speed: 'speed',
  subdirectory_arrow_left: 'subdirectory_arrow_left',
  subdirectory_arrow_right: 'subdirectory_arrow_right',
  summarize: 'summarize',
  theaters: 'theaters',
  timeline: 'timeline',
  tune: 'tune',
  undo: 'undo',
  upload_file: 'upload_file',
  visibility: 'visibility',
  visibility_off: 'visibility_off',
  warning: 'warning',
}

export function Icon({ name, className = '', ...props }: IconProps) {
  return (
    <span
      aria-hidden="true"
      {...props}
      className={`material-symbols-outlined ui-icon ${className}`.trim()}
    >
      {MATERIAL_SYMBOLS[name]}
    </span>
  )
}
